[package]
name = "cherry-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "cherry"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
cherry-protocol = { path = "../cherry-protocol" }
cherry-vt = { path = "../cherry-vt" }
clap.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
