/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bc7f2d74021170b5e4d39ff6137de851)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	DASHBOARD_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DASHBOARD_TOKEN">> {}
}
