import Darwin
import Dispatch
import Foundation

private let shellTransportDebugEnabled = ProcessInfo.processInfo.environment["CHERRY_DEBUG_INPUT"] == "1"

struct TerminalViewportSize: Equatable {
    let columns: Int
    let rows: Int
}

struct ShellIntegrationBootstrap {
    let zdotdir: String

    static func prepare(
        shellPath: String,
        homeDirectory: URL = FileManager.default.homeDirectoryForCurrentUser,
        fileManager: FileManager = .default
    ) throws -> ShellIntegrationBootstrap? {
        guard URL(fileURLWithPath: shellPath).lastPathComponent == "zsh" else {
            return nil
        }

        let directory = homeDirectory
            .appendingPathComponent("Library", isDirectory: true)
            .appendingPathComponent("Application Support", isDirectory: true)
            .appendingPathComponent("Cherry", isDirectory: true)
            .appendingPathComponent("ShellIntegration", isDirectory: true)
            .appendingPathComponent("zsh", isDirectory: true)

        try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)

        for file in zshBootstrapFiles {
            let url = directory.appendingPathComponent(file.name, isDirectory: false)
            try file.contents.write(to: url, atomically: true, encoding: .utf8)
        }

        return ShellIntegrationBootstrap(zdotdir: directory.path)
    }

    static let zshBootstrapFiles: [(name: String, contents: String)] = [
        (
            ".zshenv",
            """
            # Generated by Cherry. Do not edit.
            if [[ -n "${CHERRY_ORIGINAL_ZDOTDIR-}" ]]; then
              export ZDOTDIR="${CHERRY_ORIGINAL_ZDOTDIR}"
            else
              unset ZDOTDIR
            fi

            if [[ -f "${ZDOTDIR:-$HOME}/.zshenv" ]]; then
              source "${ZDOTDIR:-$HOME}/.zshenv"
            fi

            export ZDOTDIR="${CHERRY_BOOTSTRAP_ZDOTDIR}"
            """
        ),
        (
            ".zprofile",
            """
            # Generated by Cherry. Do not edit.
            _cherry_original_zdotdir="${CHERRY_ORIGINAL_ZDOTDIR:-$HOME}"
            if [[ -n "${CHERRY_ORIGINAL_ZDOTDIR-}" ]]; then
              export ZDOTDIR="${CHERRY_ORIGINAL_ZDOTDIR}"
            else
              unset ZDOTDIR
            fi

            if [[ -f "$_cherry_original_zdotdir/.zprofile" ]]; then
              source "$_cherry_original_zdotdir/.zprofile"
            fi

            export ZDOTDIR="${CHERRY_BOOTSTRAP_ZDOTDIR}"
            unset _cherry_original_zdotdir
            """
        ),
        (
            ".zshrc",
            """
            # Generated by Cherry. Do not edit.
            _cherry_original_zdotdir="${CHERRY_ORIGINAL_ZDOTDIR:-$HOME}"
            if [[ -n "${CHERRY_ORIGINAL_ZDOTDIR-}" ]]; then
              export ZDOTDIR="${CHERRY_ORIGINAL_ZDOTDIR}"
            else
              unset ZDOTDIR
            fi

            if [[ -f "$_cherry_original_zdotdir/.zshrc" ]]; then
              source "$_cherry_original_zdotdir/.zshrc"
            fi
            unset _cherry_original_zdotdir

            export ZDOTDIR="${CHERRY_BOOTSTRAP_ZDOTDIR}"
            if [[ "${CHERRY_DISABLE_SHELL_INTEGRATION-}" != "1" ]]; then
              source "${CHERRY_BOOTSTRAP_ZDOTDIR}/cherry-integration.zsh"
            fi

            if [[ -n "${CHERRY_ORIGINAL_ZDOTDIR-}" ]]; then
              export ZDOTDIR="${CHERRY_ORIGINAL_ZDOTDIR}"
            else
              unset ZDOTDIR
            fi
            """
        ),
        (
            "cherry-integration.zsh",
            """
            # Generated by Cherry. Do not edit.
            if [[ -o interactive && -z "${CHERRY_ZSH_INTEGRATION_SOURCED-}" ]]; then
              typeset -g CHERRY_ZSH_INTEGRATION_SOURCED=1

              _cherry_set_title() {
                emulate -L zsh
                local title="$1"
                title="${title//$'\\e'/}"
                title="${title//$'\\a'/}"
                print -n -- $'\\e]2;'"$title"$'\\a'
              }

              _cherry_set_working_directory() {
                emulate -L zsh
                local directory="$PWD"
                directory="${directory//$'\\e'/}"
                directory="${directory//$'\\a'/}"
                # Match Ghostty's shell integration: report cwd with OSC 7
                # using the kitty-shell-cwd scheme, and report on both chpwd
                # and precmd because commands may change cwd without chpwd.
                print -n -- $'\\e]7;kitty-shell-cwd://'"$HOST$directory"$'\\a'
              }

              _cherry_preexec() {
                emulate -L zsh
                _cherry_set_title "$1"
              }

              _cherry_precmd() {
                emulate -L zsh
                local directory="${PWD/#$HOME/~}"
                _cherry_set_working_directory
                _cherry_set_title "$directory"
              }

              autoload -Uz add-zsh-hook
              add-zsh-hook preexec _cherry_preexec
              add-zsh-hook chpwd _cherry_set_working_directory
              add-zsh-hook precmd _cherry_precmd
              _cherry_set_working_directory

              if [[ -n "${CHERRY_STARTUP_COMMAND-}" ]]; then
                _cherry_startup_command="$CHERRY_STARTUP_COMMAND"
                unset CHERRY_STARTUP_COMMAND
                eval "$_cherry_startup_command"
                exit $?
              fi
            fi
            """
        )
    ]
}

final class ShellProcessController: @unchecked Sendable {
    struct Configuration {
        let shellPath: String
        let workingDirectory: String
        let term: String
        let initialSize: TerminalViewportSize
        let startupCommand: String?

        init(
            shellPath: String,
            workingDirectory: String,
            term: String,
            initialSize: TerminalViewportSize,
            startupCommand: String? = nil
        ) {
            self.shellPath = shellPath
            self.workingDirectory = workingDirectory
            self.term = term
            self.initialSize = initialSize
            self.startupCommand = startupCommand
        }
    }

    static let defaultShellPath: String = {
        if let shell = ProcessInfo.processInfo.environment["SHELL"], !shell.isEmpty {
            return shell
        }

        guard let record = getpwuid(getuid()) else {
            return "/bin/zsh"
        }

        return String(cString: record.pointee.pw_shell)
    }()

    static let defaultShellName = URL(fileURLWithPath: defaultShellPath).lastPathComponent

    private let configuration: Configuration
    private let onData: (Data) -> Void
    private let onExit: (Int32) -> Void
    private let ioQueue = DispatchQueue(label: "Cherry.ShellProcess", qos: .userInitiated)
    private let urgentWriteQueue = DispatchQueue(label: "Cherry.ShellProcess.UrgentWrite", qos: .userInteractive)
    private let masterFDLock = NSLock()
    private let maximumReadBatchBytes = 4 * 1024
    private let highVolumeReadThrottleInterval: DispatchTimeInterval = .milliseconds(4)

    private var masterFD: Int32 = -1
    private var childPID: pid_t = 0
    private var readSource: DispatchSourceRead?
    private var writeSource: DispatchSourceWrite?
    private var processSource: DispatchSourceProcess?
    private var pendingWrite = Data()
    private var isReadSourcePaused = false
    private var isReadSourceThrottled = false
    private var isReadSourceSuspended = false
    private var exitReported = false
    private var isTerminating = false
    private var retainedUntilExit: ShellProcessController?

    init(
        configuration: Configuration,
        onData: @escaping (Data) -> Void,
        onExit: @escaping (Int32) -> Void
    ) throws {
        self.configuration = configuration
        self.onData = onData
        self.onExit = onExit

        try launch()
    }

    deinit {
        if childPID > 0, !exitReported {
            _ = kill(childPID, SIGHUP)
            var status: Int32 = 0
            _ = waitpid(childPID, &status, WNOHANG)
        }

        writeSource?.cancel()
        isReadSourcePaused = false
        isReadSourceThrottled = false
        resumeReadSourceIfNeeded()
        setMasterFD(-1)
        readSource?.cancel()
        processSource?.cancel()
    }

    func write(_ text: String) {
        write(Data(text.utf8))
    }

    func write(_ data: Data) {
        ioQueue.async { [self] in
            guard self.masterFD >= 0 else {
                if shellTransportDebugEnabled {
                    fputs("[pty write skipped] closed fd child=\(self.childPID)\n", stderr)
                }
                return
            }
            guard !data.isEmpty else {
                if shellTransportDebugEnabled {
                    fputs("[pty write skipped] empty payload\n", stderr)
                }
                return
            }

            self.pendingWrite.append(data)
            self.flushPendingWrites()
        }
    }

    func writeUrgent(_ data: Data) {
        guard !data.isEmpty else { return }

        urgentWriteQueue.async { [self] in
            var remaining = data
            while !remaining.isEmpty {
                switch directWriteToMaster(remaining, label: "urgent write") {
                case .wrote(let byteCount):
                    remaining.removeSubrange(0..<byteCount)
                case .interrupted:
                    continue
                case .wouldBlock:
                    write(remaining)
                    return
                case .closed, .failed:
                    return
                }
            }
        }
    }

    private enum DirectWriteResult {
        case wrote(Int)
        case interrupted
        case wouldBlock
        case closed
        case failed(Int32)
    }

    private func directWriteToMaster(_ data: Data, label: String) -> DirectWriteResult {
        masterFDLock.lock()
        defer { masterFDLock.unlock() }

        guard masterFD >= 0 else {
            if shellTransportDebugEnabled {
                fputs("[pty \(label) skipped] closed fd child=\(childPID)\n", stderr)
            }
            return .closed
        }

        let written = data.withUnsafeBytes { rawBuffer -> Int in
            guard let baseAddress = rawBuffer.baseAddress else { return 0 }
            return Darwin.write(masterFD, baseAddress, rawBuffer.count)
        }

        if written > 0 {
            if shellTransportDebugEnabled {
                let chunk = data.prefix(written)
                let rendered = chunk.map { String(format: "%02x", $0) }.joined(separator: " ")
                fputs("[pty \(label)] fd=\(masterFD) bytes=\(written) data=\(rendered)\n", stderr)
            }
            return .wrote(written)
        }

        if written == 0 {
            return .wouldBlock
        }

        let writeError = errno
        if writeError == EINTR {
            return .interrupted
        }
        if writeError == EAGAIN || writeError == EWOULDBLOCK {
            return .wouldBlock
        }

        if shellTransportDebugEnabled {
            fputs("[pty \(label) error] fd=\(masterFD) errno=\(writeError)\n", stderr)
        }
        return .failed(writeError)
    }

    func resize(columns: Int, rows: Int) {
        ioQueue.async { [weak self] in
            guard let self, self.masterFD >= 0 else { return }

            var size = winsize(
                ws_row: UInt16(rows),
                ws_col: UInt16(columns),
                ws_xpixel: 0,
                ws_ypixel: 0
            )

            _ = ioctl(self.masterFD, TIOCSWINSZ, &size)
        }
    }

    func pauseOutput() {
        ioQueue.async { [self] in
            guard self.readSource != nil else { return }
            self.isReadSourcePaused = true
            self.updateReadSourceSuspension()
        }
    }

    func resumeOutput() {
        ioQueue.async { [self] in
            guard self.readSource != nil else { return }
            self.isReadSourcePaused = false
            self.updateReadSourceSuspension()
        }
    }

    func terminate() {
        ioQueue.async { [self] in
            self.terminateOnQueue()
        }
    }

    private func launch() throws {
        var master: Int32 = -1
        var size = winsize(
            ws_row: UInt16(configuration.initialSize.rows),
            ws_col: UInt16(configuration.initialSize.columns),
            ws_xpixel: 0,
            ws_ypixel: 0
        )

        let shellPath = configuration.shellPath
        let shellName = URL(fileURLWithPath: shellPath).lastPathComponent
        let workingDirectory = configuration.workingDirectory
        let term = configuration.term
        let startupCommand = configuration.startupCommand
        let originalZDOTDIR = ProcessInfo.processInfo.environment["ZDOTDIR"]
        let shellIntegration = try? ShellIntegrationBootstrap.prepare(shellPath: shellPath)

        let pid = forkpty(&master, nil, nil, &size)
        if pid < 0 {
            throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO)
        }

        if pid == 0 {
            _ = chdir(workingDirectory)
            _ = setenv("TERM", term, 1)
            // Keep PWD aligned with the inherited cwd, matching Ghostty's
            // launch behavior so shells preserve user-facing directory text.
            _ = setenv("PWD", workingDirectory, 1)
            _ = setenv("TERM_PROGRAM", "Cherry", 1)
            _ = setenv("COLORTERM", "truecolor", 1)
            _ = setenv("INSIDE_CHERRY", "1", 1)
            if let shellIntegration {
                _ = setenv("CHERRY_BOOTSTRAP_ZDOTDIR", shellIntegration.zdotdir, 1)
                if let startupCommand, !startupCommand.isEmpty {
                    _ = setenv("CHERRY_STARTUP_COMMAND", startupCommand, 1)
                } else {
                    _ = unsetenv("CHERRY_STARTUP_COMMAND")
                }
                if let originalZDOTDIR, !originalZDOTDIR.isEmpty {
                    _ = setenv("CHERRY_ORIGINAL_ZDOTDIR", originalZDOTDIR, 1)
                } else {
                    _ = unsetenv("CHERRY_ORIGINAL_ZDOTDIR")
                }
                _ = setenv("ZDOTDIR", shellIntegration.zdotdir, 1)
            }

            if let startupCommand, shellIntegration == nil {
                let command = "exec \(startupCommand)"
                shellPath.withCString { shellPathPointer in
                    shellName.withCString { shellNamePointer in
                        "-l".withCString { loginFlagPointer in
                            "-i".withCString { interactiveFlagPointer in
                                "-c".withCString { commandFlagPointer in
                                    command.withCString { commandPointer in
                                        var arguments: [UnsafeMutablePointer<CChar>?] = [
                                            UnsafeMutablePointer(mutating: shellNamePointer),
                                            UnsafeMutablePointer(mutating: loginFlagPointer),
                                            UnsafeMutablePointer(mutating: interactiveFlagPointer),
                                            UnsafeMutablePointer(mutating: commandFlagPointer),
                                            UnsafeMutablePointer(mutating: commandPointer),
                                            nil
                                        ]

                                        execv(shellPathPointer, &arguments)
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                shellPath.withCString { shellPathPointer in
                    shellName.withCString { shellNamePointer in
                        "-l".withCString { loginFlagPointer in
                            var arguments: [UnsafeMutablePointer<CChar>?] = [
                                UnsafeMutablePointer(mutating: shellNamePointer),
                                UnsafeMutablePointer(mutating: loginFlagPointer),
                                nil
                            ]

                            execv(shellPathPointer, &arguments)
                        }
                    }
                }
            }

            _exit(127)
        }

        setMasterFD(master)
        childPID = pid

        let currentFlags = fcntl(master, F_GETFL)
        if currentFlags >= 0 {
            _ = fcntl(master, F_SETFL, currentFlags | O_NONBLOCK)
        }

        if shellTransportDebugEnabled {
            fputs("[pty launch] pid=\(pid) fd=\(master)\n", stderr)
        }

        let readSource = DispatchSource.makeReadSource(fileDescriptor: master, queue: ioQueue)
        readSource.setEventHandler { [weak self] in
            self?.drainReadableData()
        }
        readSource.setCancelHandler { [weak self] in
            if let self {
                self.closeMasterFD(master)
            } else {
                _ = close(master)
            }
        }
        self.readSource = readSource
        isReadSourcePaused = false
        isReadSourceThrottled = false
        isReadSourceSuspended = false
        readSource.resume()

        let processSource = DispatchSource.makeProcessSource(identifier: pid, eventMask: .exit, queue: ioQueue)
        processSource.setEventHandler { [weak self] in
            self?.handleExitEvent()
        }
        self.processSource = processSource
        processSource.resume()
    }

    private func drainReadableData() {
        guard masterFD >= 0 else { return }

        var buffer = [UInt8](repeating: 0, count: 4_096)
        var output = Data()
        output.reserveCapacity(maximumReadBatchBytes)
        var didCloseReadSide = false

        while output.count < maximumReadBatchBytes {
            let bytesRead = Darwin.read(masterFD, &buffer, buffer.count)
            if bytesRead > 0 {
                if shellTransportDebugEnabled {
                    fputs("[pty read] fd=\(masterFD) bytes=\(bytesRead)\n", stderr)
                }
                output.append(contentsOf: buffer.prefix(bytesRead))
                continue
            }

            if bytesRead == 0 {
                if shellTransportDebugEnabled {
                    fputs("[pty eof] fd=\(masterFD)\n", stderr)
                }
                didCloseReadSide = true
                break
            }

            if bytesRead < 0, errno == EINTR {
                continue
            }

            if bytesRead < 0, errno != EAGAIN {
                if shellTransportDebugEnabled {
                    fputs("[pty read error] fd=\(masterFD) errno=\(errno)\n", stderr)
                }
                didCloseReadSide = true
            }

            break
        }

        if !output.isEmpty {
            onData(output)
            if output.count >= maximumReadBatchBytes {
                throttleReadSourceBriefly()
            }
        }

        if didCloseReadSide {
            handleReadSideClosed()
        }
    }

    private func handleExitEvent() {
        guard !exitReported else { return }

        var status: Int32 = 0
        let waitedPID = waitpid(childPID, &status, 0)
        guard waitedPID == childPID else {
            if waitedPID < 0, errno == ECHILD {
                exitReported = true
                cleanup()
            }
            return
        }

        finishAfterProcessExit(status: status)
    }

    private func terminateOnQueue() {
        guard !isTerminating else { return }

        isTerminating = true
        retainedUntilExit = self
        pendingWrite.removeAll(keepingCapacity: true)
        cancelWriteSource()

        if childPID > 0, !exitReported {
            _ = kill(childPID, SIGHUP)
        }

        cancelReadSource()

        switch reapChildIfAvailable() {
        case .exited(let status):
            finishAfterProcessExit(status: status)
        case .unavailable:
            exitReported = true
            cleanup()
        case .stillRunning:
            if processSource == nil {
                cleanup()
            }
        }
    }

    private func handleReadSideClosed() {
        cancelReadSource()

        switch reapChildIfAvailable() {
        case .exited(let status):
            finishAfterProcessExit(status: status)
        case .unavailable:
            exitReported = true
            cleanup()
        case .stillRunning:
            if processSource == nil {
                cleanup()
            }
        }
    }

    private enum ReapResult {
        case exited(Int32)
        case stillRunning
        case unavailable
    }

    private func reapChildIfAvailable() -> ReapResult {
        guard childPID > 0, !exitReported else { return .unavailable }

        var status: Int32 = 0
        let waitedPID = waitpid(childPID, &status, WNOHANG)
        if waitedPID == childPID {
            return .exited(status)
        }

        if waitedPID == 0 {
            return .stillRunning
        }

        return errno == ECHILD ? .unavailable : .stillRunning
    }

    private func finishAfterProcessExit(status: Int32) {
        guard !exitReported else {
            cleanup()
            return
        }

        exitReported = true
        let exitCode = normalizedExitCode(status)
        if shellTransportDebugEnabled {
            fputs("[pty exit] pid=\(childPID) status=\(exitCode)\n", stderr)
        }
        if !isTerminating {
            onExit(exitCode)
        }
        cleanup()
    }

    private func flushPendingWrites() {
        guard masterFD >= 0 else {
            pendingWrite.removeAll(keepingCapacity: true)
            cancelWriteSource()
            return
        }

        while !pendingWrite.isEmpty {
            let written = pendingWrite.withUnsafeBytes { rawBuffer -> Int in
                guard let baseAddress = rawBuffer.baseAddress else { return 0 }
                return Darwin.write(masterFD, baseAddress, rawBuffer.count)
            }

            if written > 0 {
                if shellTransportDebugEnabled {
                    let chunk = pendingWrite.prefix(written)
                    let rendered = chunk.map { String(format: "%02x", $0) }.joined(separator: " ")
                    fputs("[pty write] fd=\(masterFD) bytes=\(written) data=\(rendered)\n", stderr)
                }
                pendingWrite.removeSubrange(0..<written)
                continue
            }

            if written == 0 {
                ensureWriteSource()
                return
            }

            let writeError = errno
            if writeError == EINTR {
                continue
            }

            if writeError == EAGAIN || writeError == EWOULDBLOCK {
                ensureWriteSource()
                return
            }

            if shellTransportDebugEnabled {
                fputs("[pty write error] fd=\(masterFD) errno=\(writeError)\n", stderr)
            }
            pendingWrite.removeAll(keepingCapacity: true)
            cancelWriteSource()
            return
        }

        cancelWriteSource()
    }

    private func ensureWriteSource() {
        guard writeSource == nil, masterFD >= 0 else { return }

        let writeSource = DispatchSource.makeWriteSource(fileDescriptor: masterFD, queue: ioQueue)
        writeSource.setEventHandler { [weak self] in
            self?.flushPendingWrites()
        }
        self.writeSource = writeSource
        writeSource.resume()
    }

    private func cancelWriteSource() {
        writeSource?.cancel()
        writeSource = nil
    }

    private func cancelReadSource() {
        isReadSourcePaused = false
        isReadSourceThrottled = false
        resumeReadSourceIfNeeded()
        setMasterFD(-1)
        readSource?.cancel()
        readSource = nil
    }

    private func throttleReadSourceBriefly() {
        guard readSource != nil, !isReadSourcePaused, !isReadSourceThrottled else { return }

        isReadSourceThrottled = true
        updateReadSourceSuspension()

        ioQueue.asyncAfter(deadline: .now() + highVolumeReadThrottleInterval) { [weak self] in
            guard let self else { return }
            self.isReadSourceThrottled = false
            self.updateReadSourceSuspension()
        }
    }

    private func updateReadSourceSuspension() {
        guard readSource != nil else { return }

        let shouldSuspend = isReadSourcePaused || isReadSourceThrottled
        if shouldSuspend, !isReadSourceSuspended {
            readSource?.suspend()
            isReadSourceSuspended = true
        } else if !shouldSuspend {
            resumeReadSourceIfNeeded()
        }
    }

    private func resumeReadSourceIfNeeded() {
        guard isReadSourceSuspended else { return }
        readSource?.resume()
        isReadSourceSuspended = false
    }

    private func setMasterFD(_ fileDescriptor: Int32) {
        masterFDLock.lock()
        masterFD = fileDescriptor
        masterFDLock.unlock()
    }

    private func closeMasterFD(_ fileDescriptor: Int32) {
        masterFDLock.lock()
        if masterFD == fileDescriptor {
            masterFD = -1
        }
        _ = close(fileDescriptor)
        masterFDLock.unlock()
    }

    private func cleanup() {
        if shellTransportDebugEnabled {
            fputs("[pty cleanup] pid=\(childPID) fd=\(masterFD)\n", stderr)
        }
        pendingWrite.removeAll(keepingCapacity: true)
        cancelWriteSource()
        cancelReadSource()
        processSource?.cancel()
        processSource = nil
        retainedUntilExit = nil
    }

    private func normalizedExitCode(_ status: Int32) -> Int32 {
        let signal = status & 0x7F
        if signal == 0 {
            return (status >> 8) & 0xFF
        }

        return 128 + signal
    }
}
